version: "3.7"

services:
  app_proxy:
    environment:
      # Renamed to point to the new service name
      APP_HOST: decred-ui 
      APP_PORT: 3000

  # Renamed service from 'server' to 'dcrd'
  dcrd: 
    image: decred-node:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    stop_grace_period: 5m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      APP_DECRED_NODE_RPC_USER: $APP_DECRED_NODE_RPC_USER
      APP_DECRED_NODE_RPC_PASS: $APP_DECRED_NODE_RPC_PASS
      APP_DECRED_NODE_RPC_PORT: $APP_DECRED_NODE_RPC_PORT
      APP_DECRED_NODE_P2P_PORT: $APP_DECRED_NODE_P2P_PORT
      # CRITICAL: The 'ports' block has been removed here.

  # Renamed service from 'dashboard' to 'decred-ui'
  decred-ui: 
    image: decred-dashboard:latest
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      # Updated dependency to the new service name
      - dcrd 
    environment:
      # Updated RPC host to the new service name
      DCRD_RPC_HOST: dcrd 
      DCRD_RPC_PORT: $APP_DECRED_NODE_RPC_PORT
      DCRD_RPC_USER: $APP_DECRED_NODE_RPC_USER
      DCRD_RPC_PASS: $APP_DECRED_NODE_RPC_PASS

