version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: decred-ui
      APP_PORT: 3000

  dcrd:
    image: debian:bullseye-slim
    restart: on-failure
    command: ["sleep", "infinity"]

  decred-ui:
    image: decred-dashboard:latest
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - dcrd
    environment:
      DCRD_RPC_HOST: dcrd
      DCRD_RPC_PORT: ${APP_DECRED_NODE_RPC_PORT}
      DCRD_RPC_USER: ${APP_DECRED_NODE_RPC_USER}
      DCRD_RPC_PASS: ${APP_DECRED_NODE_RPC_PASS}
    networks:
      - default

networks:
  default:
    driver: bridge
