version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: dcrd
      APP_PORT: 9109

  dcrd:
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/usr/share/nginx/html
    networks:
      - default
    ports:
      - "9109:80"

# Temporarily disable dashboard to test if it's causing installation failure
  # decred-ui:
  #   image: decred-dashboard:latest
  #   build:
  #     context: ./dashboard
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   depends_on:
  #     - dcrd
  #   environment:
  #     DCRD_RPC_HOST: dcrd
  #     DCRD_RPC_PORT: ${APP_DECRED_NODE_RPC_PORT}
  #     DCRD_RPC_USER: ${APP_DECRED_NODE_RPC_USER}
  #     DCRD_RPC_PASS: ${APP_DECRED_NODE_RPC_PASS}
  #   networks:
  #     - default

networks:
  default:
    driver: bridge
