version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: dashboard
      APP_PORT: 3000

  server:
    image: decred-node:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    stop_grace_period: 5m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      APP_DECRED_NODE_RPC_USER: $APP_DECRED_NODE_RPC_USER
      APP_DECRED_NODE_RPC_PASS: $APP_DECRED_NODE_RPC_PASS
      APP_DECRED_NODE_RPC_PORT: $APP_DECRED_NODE_RPC_PORT
      APP_DECRED_NODE_P2P_PORT: $APP_DECRED_NODE_P2P_PORT

  dashboard:
    image: decred-dashboard:latest
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - server
    environment:
      DCRD_RPC_HOST: server
      DCRD_RPC_PORT: $APP_DECRED_NODE_RPC_PORT
      DCRD_RPC_USER: $APP_DECRED_NODE_RPC_USER
      DCRD_RPC_PASS: $APP_DECRED_NODE_RPC_PASS

