version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: dcrd
      APP_PORT: 9109

  dcrd:
    image: decred-node:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    stop_grace_period: 5m
    volumes:
      - ${APP_DATA_DIR}/data:/home/decred/.dcrd
    command:
      - "--rpclisten=0.0.0.0:${APP_DECRED_NODE_RPC_PORT}"
      - "--listen=0.0.0.0:${APP_DECRED_NODE_P2P_PORT}"
      - "--rpcuser=${APP_DECRED_NODE_RPC_USER}"
      - "--rpcpass=${APP_DECRED_NODE_RPC_PASS}"
      - "--nofilelogging"
      - "--datadir=/home/decred/.dcrd"
    networks:
      - default
    ports:
      - "${APP_DECRED_NODE_P2P_PORT}:${APP_DECRED_NODE_P2P_PORT}"
      - "${APP_DECRED_NODE_RPC_PORT}:${APP_DECRED_NODE_RPC_PORT}"

# Temporarily disable dashboard to test if it's causing installation failure
  # decred-ui:
  #   image: decred-dashboard:latest
  #   build:
  #     context: ./dashboard
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   depends_on:
  #     - dcrd
  #   environment:
  #     DCRD_RPC_HOST: dcrd
  #     DCRD_RPC_PORT: ${APP_DECRED_NODE_RPC_PORT}
  #     DCRD_RPC_USER: ${APP_DECRED_NODE_RPC_USER}
  #     DCRD_RPC_PASS: ${APP_DECRED_NODE_RPC_PASS}
  #   networks:
  #     - default

networks:
  default:
    driver: bridge
