version: "3.7"

services:
  server:
    image: decred-node:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    stop_grace_period: 5m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    networks:
      default:
        ipv4_address: $APP_DECRED_NODE_IP
    environment:
      APP_DECRED_NODE_RPC_USER: $APP_DECRED_NODE_RPC_USER
      APP_DECRED_NODE_RPC_PASS: $APP_DECRED_NODE_RPC_PASS
      APP_DECRED_NODE_RPC_PORT: $APP_DECRED_NODE_RPC_PORT
      APP_DECRED_NODE_P2P_PORT: $APP_DECRED_NODE_P2P_PORT
    ports:
      - "$APP_DECRED_NODE_P2P_PORT:$APP_DECRED_NODE_P2P_PORT"

  dashboard:
    image: decred-dashboard:latest
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - server
    environment:
      DCRD_RPC_HOST: $APP_DECRED_NODE_IP
      DCRD_RPC_PORT: $APP_DECRED_NODE_RPC_PORT
      DCRD_RPC_USER: $APP_DECRED_NODE_RPC_USER
      DCRD_RPC_PASS: $APP_DECRED_NODE_RPC_PASS
    ports:
      - "3000:3000"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.21.21.0/24
